vich_uploader:
    db_driver: orm 

    # metadata:
    #     type: attribute

    mappings:
        images_files_products:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
