controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

_not_found:
    path: /{url}
    defaults: { _controller: 'App\Controller\ErrorController::notFound' }
    requirements:
        url: .*
